version: "1"
metrics:
  - name: "name"
    exclude: ["Ronan", "Candice"]
    coherentWith: ["name", "surname"]
    constraints:
      maskingRate:
        shouldEqual: 1
      coherentRate:
        shouldBeGreaterThan: 0.95
