FROM adrienaury/go-devcontainer-ci:v3.0

USER root

RUN apk add --update --progress --no-cache make gomplate

ARG VERSION_MILLER=6.2.0
RUN    wget -nv -O- https://github.com/johnkerl/miller/releases/download/v${VERSION_MILLER}/miller-${VERSION_MILLER}-linux-amd64.tar.gz | tar xz --strip-components 1 -C /usr/bin miller-${VERSION_MILLER}-linux-amd64/mlr \
    && chmod +x /usr/bin/mlr
